/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bicicleta.Bicicleta;
import categoria.Categoria;
import fabricante.Fabricante;
import fachada.Fachada;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import outros.IntegerFilter;
import outros.MyTableModel;

/**
 *
 * @author Matheus
 */
public class BicicletaGUI extends javax.swing.JFrame {

    /**
     * Creates new form BicicletaGUI
     */
    private final Fachada fachada = new Fachada();
    private ArrayList<Bicicleta> bicicletas;
    private final MyTableModel modeloAlterar = new MyTableModel(0, "Cód. Bicicleta", "Nome", "Ano", "Cor", "Pneu", "CNPJ", "Fabricante", "Cód. Categoria", "Categoria");
    private ArrayList<Fabricante> fabricantes;
    private ArrayList<Categoria> categorias;
    private final DefaultComboBoxModel modeloFabricante = new DefaultComboBoxModel();
    private final DefaultComboBoxModel modeloFabricanteEdit = new DefaultComboBoxModel();
    private final DefaultComboBoxModel modeloCategoria = new DefaultComboBoxModel();
    private final DefaultComboBoxModel modeloCategoriaEdit = new DefaultComboBoxModel();
    private int selectedRow;
    private int previousTab = -1, currentTab = -1;

    public BicicletaGUI() {
        initComponents();
        jTabbedPane1.setEnabledAt(2, false);
        carregarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCadastrar = new javax.swing.JPanel();
        jLabelCod = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelAno = new javax.swing.JLabel();
        jFTextFieldAno = new javax.swing.JFormattedTextField();
        jLabelCor = new javax.swing.JLabel();
        jTextFieldCor = new javax.swing.JTextField();
        jLabelPneu = new javax.swing.JLabel();
        jTextFieldPneu = new javax.swing.JTextField();
        jLabelFab = new javax.swing.JLabel();
        jLabelPlusFab = new javax.swing.JLabel();
        jLabelRefFab = new javax.swing.JLabel();
        jCBoxFab = new javax.swing.JComboBox<>();
        jLabelCat = new javax.swing.JLabel();
        jLabelPlusCat = new javax.swing.JLabel();
        jLabelRefCat = new javax.swing.JLabel();
        jCBoxCat = new javax.swing.JComboBox<>();
        jBtnCadastrar = new javax.swing.JButton();
        jPanelListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelWarning = new javax.swing.JLabel();
        jBtnDeletar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jPanelEditar = new javax.swing.JPanel();
        jLabelCodEdit = new javax.swing.JLabel();
        jTextFieldCodEdit = new javax.swing.JTextField();
        jLabelNomeEdit = new javax.swing.JLabel();
        jTextFieldNomeEdit = new javax.swing.JTextField();
        jLabelAnoEdit = new javax.swing.JLabel();
        jFTextFieldAnoEdit = new javax.swing.JFormattedTextField();
        jLabelCorEdit = new javax.swing.JLabel();
        jTextFieldCorEdit = new javax.swing.JTextField();
        jLabelPneuEdit = new javax.swing.JLabel();
        jTextFieldPneuEdit = new javax.swing.JTextField();
        jLabelFabEdit = new javax.swing.JLabel();
        jCBoxFabricanteEdit = new javax.swing.JComboBox<>();
        jLabelCatEdit = new javax.swing.JLabel();
        jCBoxCategoriaEdit = new javax.swing.JComboBox<>();
        jBtnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bicicleta");
        setResizable(false);

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabelCod.setText("Código:");

        jTextFieldCod.setDocument(new IntegerFilter());
        jTextFieldCod.setText("0");
        jTextFieldCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodFocusLost(evt);
            }
        });

        jLabelNome.setText("Nome:");

        jLabelAno.setText("Ano:");

        try {
            jFTextFieldAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCor.setText("Cor:");

        jLabelPneu.setText("Pneu:");

        jLabelFab.setText("Fabricante:");

        jLabelPlusFab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/add.png"))); // NOI18N
        jLabelPlusFab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPlusFabMouseClicked(evt);
            }
        });

        jLabelRefFab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/arrow_refresh_small.png"))); // NOI18N
        jLabelRefFab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRefFabMouseClicked(evt);
            }
        });

        jLabelCat.setText("Categoria:");

        jLabelPlusCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/add.png"))); // NOI18N
        jLabelPlusCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPlusCatMouseClicked(evt);
            }
        });

        jLabelRefCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/arrow_refresh_small.png"))); // NOI18N
        jLabelRefCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRefCatMouseClicked(evt);
            }
        });

        jBtnCadastrar.setText("Cadastrar");
        jBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastrarLayout = new javax.swing.GroupLayout(jPanelCadastrar);
        jPanelCadastrar.setLayout(jPanelCadastrarLayout);
        jPanelCadastrarLayout.setHorizontalGroup(
            jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCod)
                            .addComponent(jLabelAno)
                            .addComponent(jLabelPneu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTextFieldAno, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jTextFieldPneu)
                            .addComponent(jTextFieldCod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTextFieldCor)))
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCat)
                            .addComponent(jLabelFab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBoxCat, 0, 318, Short.MAX_VALUE)
                            .addComponent(jCBoxFab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelPlusFab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRefFab))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastrarLayout.createSequentialGroup()
                                .addComponent(jLabelPlusCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRefCat)))))
                .addContainerGap())
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jBtnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastrarLayout.setVerticalGroup(
            jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCod)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAno)
                    .addComponent(jLabelCor)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPneu)
                    .addComponent(jTextFieldPneu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastrarLayout.createSequentialGroup()
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlusFab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRefFab, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelFab)
                                .addComponent(jCBoxFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCat)
                            .addComponent(jCBoxCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPlusCat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRefCat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jBtnCadastrar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastrar", jPanelCadastrar);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelWarning.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelWarning.setForeground(new java.awt.Color(255, 51, 51));
        jLabelWarning.setText("OBS.: A alteração ocorre na linha selecionada.");

        jBtnDeletar.setText("Deletar");
        jBtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeletarActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabelWarning))
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jBtnDeletar)
                        .addGap(36, 36, 36)
                        .addComponent(jBtnEditar)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWarning)
                .addGap(11, 11, 11)
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDeletar)
                    .addComponent(jBtnEditar)))
        );

        jTabbedPane1.addTab("Listar", jPanelListar);

        jLabelCodEdit.setText("Código:");

        jTextFieldCodEdit.setEditable(false);
        jTextFieldCodEdit.setDocument(new IntegerFilter());
        jTextFieldCodEdit.setText("0");

        jLabelNomeEdit.setText("Nome:");

        jLabelAnoEdit.setText("Ano:");

        try {
            jFTextFieldAnoEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCorEdit.setText("Cor:");

        jLabelPneuEdit.setText("Pneu:");

        jLabelFabEdit.setText("Fabricante:");

        jLabelCatEdit.setText("Categoria:");

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditarLayout = new javax.swing.GroupLayout(jPanelEditar);
        jPanelEditar.setLayout(jPanelEditarLayout);
        jPanelEditarLayout.setHorizontalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCodEdit)
                            .addComponent(jLabelAnoEdit)
                            .addComponent(jLabelPneuEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFTextFieldAnoEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jTextFieldPneuEdit)
                            .addComponent(jTextFieldCodEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCorEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNomeEdit, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTextFieldCorEdit)))
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelCatEdit)
                            .addComponent(jLabelFabEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBoxFabricanteEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCBoxCategoriaEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditarLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jBtnSalvar)
                .addGap(190, 190, 190))
        );
        jPanelEditarLayout.setVerticalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodEdit)
                    .addComponent(jTextFieldNomeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomeEdit)
                    .addComponent(jTextFieldCodEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFTextFieldAnoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnoEdit)
                    .addComponent(jLabelCorEdit)
                    .addComponent(jTextFieldCorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPneuEdit)
                    .addComponent(jTextFieldPneuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFabEdit)
                    .addComponent(jCBoxFabricanteEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCatEdit)
                    .addComponent(jCBoxCategoriaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jBtnSalvar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editar", jPanelEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            Bicicleta bicicleta = new Bicicleta();
            bicicleta.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
            bicicleta.setDescricao(jTextFieldNome.getText());
            bicicleta.setAno(jFTextFieldAno.getText());
            bicicleta.setCor(jTextFieldCor.getText());
            bicicleta.setPneu(jTextFieldPneu.getText());
            bicicleta.setFabricante(fabricantes.get(jCBoxFab.getSelectedIndex()));
            bicicleta.setCategoria(categorias.get(jCBoxCat.getSelectedIndex()));

            fachada.inserir(bicicleta);
            JOptionPane.showMessageDialog(this, "Bicicleta inserida com sucesso.");

            adicionarLinha(bicicleta);
            resetarCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnCadastrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selectedRow = jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeletarActionPerformed
        // TODO add your handling code here:
        try {
            Bicicleta bicicleta = getValues();

            fachada.remover(bicicleta);
            JOptionPane.showMessageDialog(this, "Bicicleta removida com sucesso.");

            modeloAlterar.removeRow(selectedRow);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnDeletarActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        try {
            Bicicleta bicicleta = getValues();

            jTextFieldCodEdit.setText(bicicleta.getCodigo() + "");
            jTextFieldNomeEdit.setText(bicicleta.getDescricao());
            jFTextFieldAnoEdit.setText(bicicleta.getAno());
            jTextFieldCorEdit.setText(bicicleta.getCor());
            jTextFieldPneuEdit.setText(bicicleta.getPneu());
            int fabricante = findFabricante(bicicleta);
            jCBoxFabricanteEdit.setSelectedIndex(fabricante);
            int categoria = findCategoria(bicicleta);
            jCBoxCategoriaEdit.setSelectedIndex(categoria);

            jTabbedPane1.setEnabledAt(2, true);
            jTabbedPane1.setSelectedIndex(2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            Bicicleta bicicleta = getValues();

            bicicleta.setCodigo(Integer.parseInt(jTextFieldCodEdit.getText()));
            bicicleta.setDescricao(jTextFieldNomeEdit.getText());
            bicicleta.setAno(jFTextFieldAnoEdit.getText());
            bicicleta.setCor(jTextFieldCorEdit.getText());
            bicicleta.setPneu(jTextFieldPneuEdit.getText());
            bicicleta.setFabricante(fabricantes.get(jCBoxFabricanteEdit.getSelectedIndex()));
            bicicleta.setCategoria(categorias.get(jCBoxCategoriaEdit.getSelectedIndex()));

            fachada.atualizar(bicicleta);
            JOptionPane.showMessageDialog(this, "Bicicleta alterada com sucesso.");

            atualizarLinha(bicicleta);
            resetarCamposEdit();

            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane1.setEnabledAt(2, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        previousTab = currentTab;
        currentTab = jTabbedPane1.getSelectedIndex();
        if (previousTab == 2) {
            jTabbedPane1.setEnabledAt(2, false);
        }
        if (currentTab == 0) {
            jTextFieldCod.requestFocusInWindow();
            jTextFieldCod.selectAll();
        } else if (currentTab == 2) {
            jTextFieldNomeEdit.requestFocusInWindow();
            jTextFieldNomeEdit.selectAll();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jLabelPlusFabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlusFabMouseClicked
        // TODO add your handling code here:
        new FabricanteGUI().setVisible(true);
    }//GEN-LAST:event_jLabelPlusFabMouseClicked

    private void jLabelPlusCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlusCatMouseClicked
        // TODO add your handling code here:
        new CategoriaGUI().setVisible(true);
    }//GEN-LAST:event_jLabelPlusCatMouseClicked

    private void jLabelRefFabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRefFabMouseClicked
        // TODO add your handling code here:
        carregarComponentes();
        JOptionPane.showMessageDialog(this, "Componentes atualizados.");
    }//GEN-LAST:event_jLabelRefFabMouseClicked

    private void jLabelRefCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRefCatMouseClicked
        // TODO add your handling code here:
        carregarComponentes();
        JOptionPane.showMessageDialog(this, "Componentes atualizados.");
    }//GEN-LAST:event_jLabelRefCatMouseClicked

    private void jTextFieldCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodFocusLost
        // TODO add your handling code here:
        if (jTextFieldCod.getText().isEmpty()) {
            jTextFieldCod.setText("0");
        }
    }//GEN-LAST:event_jTextFieldCodFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BicicletaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JButton jBtnDeletar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JComboBox<String> jCBoxCat;
    private javax.swing.JComboBox<String> jCBoxCategoriaEdit;
    private javax.swing.JComboBox<String> jCBoxFab;
    private javax.swing.JComboBox<String> jCBoxFabricanteEdit;
    private javax.swing.JFormattedTextField jFTextFieldAno;
    private javax.swing.JFormattedTextField jFTextFieldAnoEdit;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelAnoEdit;
    private javax.swing.JLabel jLabelCat;
    private javax.swing.JLabel jLabelCatEdit;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelCodEdit;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCorEdit;
    private javax.swing.JLabel jLabelFab;
    private javax.swing.JLabel jLabelFabEdit;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeEdit;
    private javax.swing.JLabel jLabelPlusCat;
    private javax.swing.JLabel jLabelPlusFab;
    private javax.swing.JLabel jLabelPneu;
    private javax.swing.JLabel jLabelPneuEdit;
    private javax.swing.JLabel jLabelRefCat;
    private javax.swing.JLabel jLabelRefFab;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPanel jPanelCadastrar;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldCodEdit;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldCorEdit;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeEdit;
    private javax.swing.JTextField jTextFieldPneu;
    private javax.swing.JTextField jTextFieldPneuEdit;
    // End of variables declaration//GEN-END:variables

    private void resetarCampos() {
        jTextFieldCod.setText("0");
        jTextFieldNome.setText("");
        jFTextFieldAno.setText("");
        jTextFieldCor.setText("");
        jTextFieldPneu.setText("");
        jCBoxFab.setSelectedIndex(0);
        jCBoxCat.setSelectedIndex(0);
        jTextFieldCod.requestFocusInWindow();
    }

    private void resetarCamposEdit() {
        jTextFieldCodEdit.setText("0");
        jTextFieldNomeEdit.setText("");
        jFTextFieldAnoEdit.setText("");
        jTextFieldCorEdit.setText("");
        jTextFieldPneuEdit.setText("");
        jCBoxFabricanteEdit.setSelectedIndex(0);
        jCBoxCategoriaEdit.setSelectedIndex(0);
    }

    private void adicionarLinha(Bicicleta bicicleta) {
        modeloAlterar.addRow(
                new Object[]{bicicleta.getCodigo(), bicicleta.getDescricao(), bicicleta.getAno(),
                    bicicleta.getCor(), bicicleta.getPneu(), bicicleta.getFabricante().getCnpj(), getFabricanteNome(bicicleta.getFabricante()),
                    bicicleta.getCategoria().getCodigo(), bicicleta.getCategoria().getDescricao()}
        );
    }

    private void carregarTabela() {
        modeloAlterar.setRowCount(0);
        try {
            bicicletas = fachada.listar(new Bicicleta());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        for (Bicicleta b : bicicletas) {
            adicionarLinha(b);
        }
        jTable1.setModel(modeloAlterar);
    }

    private String getFabricanteNome(Fabricante fabricante) {
        String nome = fabricante.getRazaoSocial();
        if (!fabricante.getNomeFantasia().equals("")) {
            nome += " / " + fabricante.getNomeFantasia();
        }
        return nome;
    }

    private Bicicleta getValues() throws Exception {
        if (selectedRow < 0) {
            throw new Exception("Nenhuma linha selecionada.");
        }
        Bicicleta bicicleta = new Bicicleta();
        //"Cód. Bicicleta_0", "Nome_1", "Ano_2", "Cor_3", "Pneu_4", "CNPJ_5", "Fabricante_6", "Cód. Categoria_7", "Categoria_8"
        bicicleta.setCodigo(Integer.parseInt(jTable1.getValueAt(selectedRow, 0) + ""));
        bicicleta.setDescricao(jTable1.getValueAt(selectedRow, 1) + "");
        bicicleta.setAno(jTable1.getValueAt(selectedRow, 2) + "");
        bicicleta.setCor(jTable1.getValueAt(selectedRow, 3) + "");
        bicicleta.setPneu(jTable1.getValueAt(selectedRow, 4) + "");

        Fabricante fabricante = new Fabricante();
        fabricante.setCnpj(jTable1.getValueAt(selectedRow, 5) + "");
        bicicleta.setFabricante(fabricante);

        Categoria categoria = new Categoria();
        categoria.setCodigo(Integer.parseInt(jTable1.getValueAt(selectedRow, 7) + ""));
        bicicleta.setCategoria(categoria);

        return bicicleta;
    }

    private int findFabricante(Bicicleta b) {
        String cpnj = b.getFabricante().getCnpj();
        int found = -1;

        for (int i = 0; i < fabricantes.size(); i++) {
            String cnpjFound = fabricantes.get(i).getCnpj();
            if (cnpjFound.equals(cpnj)) {
                found = i;
                break;
            }
        }

        return found;
    }

    private int findCategoria(Bicicleta b) {
        int codigo = b.getCategoria().getCodigo();
        int found = -1;

        for (int i = 0; i < categorias.size(); i++) {
            int codigoFound = categorias.get(i).getCodigo();
            if (codigoFound == codigo) {
                found = i;
                break;
            }
        }
        return found;
    }

    private void carregarFabricantes() {
        modeloFabricante.removeAllElements();
        modeloFabricanteEdit.removeAllElements();
        try {
            fabricantes = fachada.listar(new Fabricante());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        for (Fabricante f : fabricantes) {
            String nome = getFabricanteNome(f);
            modeloFabricante.addElement(nome);
            modeloFabricanteEdit.addElement(nome);
        }
        jCBoxFab.setModel(modeloFabricante);
        jCBoxFabricanteEdit.setModel(modeloFabricanteEdit);
    }

    private void carregarCategorias() {
        modeloCategoria.removeAllElements();
        modeloCategoriaEdit.removeAllElements();
        try {
            categorias = fachada.listar(new Categoria());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        for (Categoria c : categorias) {
            modeloCategoria.addElement(c.getDescricao());
            modeloCategoriaEdit.addElement(c.getDescricao());
        }
        jCBoxCat.setModel(modeloCategoria);
        jCBoxCategoriaEdit.setModel(modeloCategoriaEdit);
    }

    private void atualizarLinha(Bicicleta bicicleta) {
        if (bicicleta.getFabricante().getNomeFantasia() == null) {
            bicicleta.getFabricante().setNomeFantasia("");
        }
        //"Cód. Bicicleta_0", "Nome_1", "Ano_2", "Cor_3", "Pneu_4", "CNPJ_5", "Fabricante_6", "Cód. Categoria_7", "Categoria_8"
        jTable1.setValueAt(bicicleta.getDescricao(), selectedRow, 1);
        jTable1.setValueAt(bicicleta.getAno(), selectedRow, 2);
        jTable1.setValueAt(bicicleta.getCor(), selectedRow, 3);
        jTable1.setValueAt(bicicleta.getPneu(), selectedRow, 4);
        jTable1.setValueAt(bicicleta.getFabricante().getCnpj(), selectedRow, 5);
        jTable1.setValueAt(getFabricanteNome(bicicleta.getFabricante()), selectedRow, 6);
        jTable1.setValueAt(bicicleta.getCategoria().getCodigo(), selectedRow, 7);
        jTable1.setValueAt(bicicleta.getCategoria().getDescricao(), selectedRow, 8);
    }

    private void carregarComponentes() {
        carregarFabricantes();
        carregarCategorias();
        carregarTabela();
        selectedRow = -1;
    }

}
