/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import fabricante.Fabricante;
import fachada.Fachada;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import outros.IntegerFilter;
import outros.MyTableModel;

/**
 *
 * @author Matheus
 */
public class FabricanteGUI extends javax.swing.JFrame {

    /**
     * Creates new form FabricanteGUI
     */
    private final Fachada fachada = new Fachada();
    private ArrayList<Fabricante> fabricantes = new ArrayList<>();
    private final MyTableModel modeloAlterar = new MyTableModel(0, "CPNJ", "Nome Fantasia", "Razão Social", "Telefone", "CEP", "Logradouro", "Número", "Complemento", "Bairro", "Cidade", "UF");
    //private final DefaultComboBoxModel modeloUF = new DefaultComboBoxModel(new String[]{"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO"});
    private int selectedRow = -1;
    private int previousTab = -1, currentTab = -1;

    public FabricanteGUI() {
        initComponents();
        jTabbedPane1.setEnabledAt(2, false);
        //editarTabela();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCadastar = new javax.swing.JPanel();
        jLabelCNPJ = new javax.swing.JLabel();
        jFTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jLabelNmFant = new javax.swing.JLabel();
        jTextFieldNmFant = new javax.swing.JTextField();
        jLabelRazaoSoc = new javax.swing.JLabel();
        jTextFieldRazaoSoc = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        jFTextFieldTel = new javax.swing.JFormattedTextField();
        jLabelCEP = new javax.swing.JLabel();
        jFTextFieldCEP = new javax.swing.JFormattedTextField();
        jLabelLogr = new javax.swing.JLabel();
        jTextFieldLogr = new javax.swing.JTextField();
        jLabelNum = new javax.swing.JLabel();
        jTextFieldNum = new javax.swing.JTextField();
        jLabelComp = new javax.swing.JLabel();
        jTextFieldComp = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelUF = new javax.swing.JLabel();
        jCBoxUF = new javax.swing.JComboBox<>();
        jBtnCadastrar = new javax.swing.JButton();
        jPanelListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelWarning = new javax.swing.JLabel();
        jBtnDeletar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jPanelEditar = new javax.swing.JPanel();
        jLabelCNPJEdit = new javax.swing.JLabel();
        jFTextFieldCNPJEdit = new javax.swing.JFormattedTextField();
        jLabelNmFantEdit = new javax.swing.JLabel();
        jTextFieldNmFantEdit = new javax.swing.JTextField();
        jLabelRazaoSocEdit = new javax.swing.JLabel();
        jTextFieldRazaoSocEdit = new javax.swing.JTextField();
        jLabelTelEdit = new javax.swing.JLabel();
        jFTextFieldTelEdit = new javax.swing.JFormattedTextField();
        jLabelCEPEdit = new javax.swing.JLabel();
        jFTextFieldCEPEdit = new javax.swing.JFormattedTextField();
        jLabelLogrEdit = new javax.swing.JLabel();
        jTextFieldLogrEdit = new javax.swing.JTextField();
        jLabelNumEdit = new javax.swing.JLabel();
        jTextFieldNumEdit = new javax.swing.JTextField();
        jLabelCompEdit = new javax.swing.JLabel();
        jTextFieldCompEdit = new javax.swing.JTextField();
        jLabelBairroEdit = new javax.swing.JLabel();
        jTextFieldBairroEdit = new javax.swing.JTextField();
        jLabelCidadeEdit = new javax.swing.JLabel();
        jTextFieldCidadeEdit = new javax.swing.JTextField();
        jLabelUFEdit = new javax.swing.JLabel();
        jCBoxUFEdit = new javax.swing.JComboBox<>();
        jBtnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fabricante");
        setResizable(false);

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabelCNPJ.setText("CNPJ:");

        try {
            jFTextFieldCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelNmFant.setText("Nome Fantasia:");

        jLabelRazaoSoc.setText("Razão Social:");

        jLabelTel.setText("Telefone:");

        try {
            jFTextFieldTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCEP.setText("CEP:");

        try {
            jFTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelLogr.setText("Logradouro:");

        jLabelNum.setText("Número:");

        jTextFieldNum.setDocument(new IntegerFilter());
        jTextFieldNum.setText("0");
        jTextFieldNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumFocusLost(evt);
            }
        });

        jLabelComp.setText("Complemento:");

        jLabelBairro.setText("Bairro:");

        jLabelCidade.setText("Cidade:");

        jLabelUF.setText("UF:");

        jCBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        jBtnCadastrar.setText("Cadastrar");
        jBtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastarLayout = new javax.swing.GroupLayout(jPanelCadastar);
        jPanelCadastar.setLayout(jPanelCadastarLayout);
        jPanelCadastarLayout.setHorizontalGroup(
            jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastarLayout.createSequentialGroup()
                        .addComponent(jLabelCNPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastarLayout.createSequentialGroup()
                        .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRazaoSoc)
                            .addComponent(jLabelCEP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelBairro, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRazaoSoc)
                            .addComponent(jFTextFieldCEP)
                            .addGroup(jPanelCadastarLayout.createSequentialGroup()
                                .addComponent(jCBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addComponent(jTextFieldNum)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNmFant)
                    .addComponent(jLabelTel)
                    .addComponent(jLabelLogr)
                    .addComponent(jLabelComp)
                    .addComponent(jLabelCidade))
                .addGap(7, 7, 7)
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNmFant, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jFTextFieldTel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jTextFieldLogr)
                    .addComponent(jTextFieldComp)
                    .addComponent(jTextFieldCidade))
                .addContainerGap())
            .addGroup(jPanelCadastarLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jBtnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastarLayout.setVerticalGroup(
            jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCNPJ)
                    .addComponent(jFTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNmFant)
                    .addComponent(jTextFieldNmFant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRazaoSoc)
                    .addComponent(jTextFieldRazaoSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTel)
                    .addComponent(jFTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCEP)
                    .addComponent(jFTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNum)
                    .addComponent(jLabelComp)
                    .addComponent(jTextFieldComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairro)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUF)
                    .addComponent(jCBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", jPanelCadastar);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelWarning.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelWarning.setForeground(new java.awt.Color(255, 51, 51));
        jLabelWarning.setText("OBS.: A alteração ocorre na linha selecionada.");

        jBtnDeletar.setText("Deletar");
        jBtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeletarActionPerformed(evt);
            }
        });

        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabelWarning))
                    .addGroup(jPanelListarLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jBtnDeletar)
                        .addGap(36, 36, 36)
                        .addComponent(jBtnEditar)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelWarning)
                .addGap(11, 11, 11)
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDeletar)
                    .addComponent(jBtnEditar)))
        );

        jTabbedPane1.addTab("Listar", jPanelListar);

        jLabelCNPJEdit.setText("CNPJ:");

        jFTextFieldCNPJEdit.setEditable(false);
        try {
            jFTextFieldCNPJEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelNmFantEdit.setText("Nome Fantasia:");

        jLabelRazaoSocEdit.setText("Razão Social:");

        jLabelTelEdit.setText("Telefone:");

        try {
            jFTextFieldTelEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCEPEdit.setText("CEP:");

        try {
            jFTextFieldCEPEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelLogrEdit.setText("Logradouro:");

        jLabelNumEdit.setText("Número:");

        jTextFieldNumEdit.setDocument(new IntegerFilter());
        jTextFieldNumEdit.setText("0");
        jTextFieldNumEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumEditFocusLost(evt);
            }
        });

        jLabelCompEdit.setText("Complemento:");

        jLabelBairroEdit.setText("Bairro:");

        jLabelCidadeEdit.setText("Cidade:");

        jLabelUFEdit.setText("UF:");

        jCBoxUFEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditarLayout = new javax.swing.GroupLayout(jPanelEditar);
        jPanelEditar.setLayout(jPanelEditarLayout);
        jPanelEditarLayout.setHorizontalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jBtnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addComponent(jLabelCNPJEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFTextFieldCNPJEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEditarLayout.createSequentialGroup()
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRazaoSocEdit)
                            .addComponent(jLabelCEPEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNumEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUFEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelBairroEdit, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRazaoSocEdit)
                            .addComponent(jFTextFieldCEPEdit)
                            .addGroup(jPanelEditarLayout.createSequentialGroup()
                                .addComponent(jCBoxUFEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addComponent(jTextFieldNumEdit)
                            .addComponent(jTextFieldBairroEdit))))
                .addGap(18, 18, 18)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNmFantEdit)
                    .addComponent(jLabelTelEdit)
                    .addComponent(jLabelLogrEdit)
                    .addComponent(jLabelCompEdit)
                    .addComponent(jLabelCidadeEdit))
                .addGap(6, 6, 6)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCidadeEdit)
                    .addComponent(jTextFieldNmFantEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jFTextFieldTelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jTextFieldLogrEdit)
                    .addComponent(jTextFieldCompEdit))
                .addContainerGap())
        );
        jPanelEditarLayout.setVerticalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCNPJEdit)
                    .addComponent(jFTextFieldCNPJEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNmFantEdit)
                    .addComponent(jTextFieldNmFantEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRazaoSocEdit)
                    .addComponent(jTextFieldRazaoSocEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelEdit)
                    .addComponent(jFTextFieldTelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCEPEdit)
                    .addComponent(jFTextFieldCEPEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogrEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogrEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumEdit)
                    .addComponent(jLabelCompEdit)
                    .addComponent(jTextFieldCompEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBairroEdit)
                    .addComponent(jTextFieldBairroEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCidadeEdit)
                    .addComponent(jTextFieldCidadeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUFEdit)
                    .addComponent(jCBoxUFEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jBtnSalvar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editar", jPanelEditar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumFocusLost
        // TODO add your handling code here:
        if (jTextFieldNum.getText().isEmpty()) {
            jTextFieldNum.setText("0");
        }
    }//GEN-LAST:event_jTextFieldNumFocusLost

    private void jBtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            Fabricante fabricante = new Fabricante();

            fabricante.setCnpj(jFTextFieldCNPJ.getText());
            fabricante.setNomeFantasia(jTextFieldNmFant.getText());
            fabricante.setRazaoSocial(jTextFieldRazaoSoc.getText());
            fabricante.setTelefone(jFTextFieldTel.getText());
            fabricante.setCep(jFTextFieldCEP.getText());
            fabricante.setLogradouro(jTextFieldLogr.getText());
            fabricante.setNumero(Integer.parseInt(jTextFieldNum.getText()));
            fabricante.setComplemento(jTextFieldComp.getText());
            fabricante.setComplemento(jTextFieldComp.getText());
            fabricante.setBairro(jTextFieldBairro.getText());
            fabricante.setCidade(jTextFieldCidade.getText());
            fabricante.setUf(jCBoxUF.getSelectedItem() + "");

            fachada.inserir(fabricante);
            JOptionPane.showMessageDialog(this, "Fabricante inserido com sucesso.");

            adicionarLinha(fabricante);
            resetarCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnCadastrarActionPerformed

    private void jBtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeletarActionPerformed
        // TODO add your handling code here:
        try {
            Fabricante fabricante = getValues();

            fachada.remover(fabricante);
            JOptionPane.showMessageDialog(this, "Fabricante removido com sucesso.");

            modeloAlterar.removeRow(selectedRow);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnDeletarActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        // TODO add your handling code here:
        try {
            Fabricante fabricante = getValues();

            jFTextFieldCNPJEdit.setText(fabricante.getCnpj());
            jTextFieldNmFantEdit.setText(fabricante.getNomeFantasia());
            jTextFieldRazaoSocEdit.setText(fabricante.getRazaoSocial());
            jFTextFieldTelEdit.setText(fabricante.getTelefone());
            jFTextFieldCEPEdit.setText(fabricante.getCep());
            jTextFieldLogrEdit.setText(fabricante.getLogradouro());
            jTextFieldNumEdit.setText(fabricante.getNumero() + "");
            jTextFieldCompEdit.setText(fabricante.getComplemento());
            jTextFieldBairroEdit.setText(fabricante.getBairro());
            jTextFieldCidadeEdit.setText(fabricante.getCidade());
            jCBoxUFEdit.setSelectedItem(fabricante.getUf());

            jTabbedPane1.setEnabledAt(2, true);
            jTabbedPane1.setSelectedIndex(2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            Fabricante fabricante = getValues();

            fabricante.setCnpj(jFTextFieldCNPJEdit.getText());
            fabricante.setNomeFantasia(jTextFieldNmFantEdit.getText());
            fabricante.setRazaoSocial(jTextFieldRazaoSocEdit.getText());
            fabricante.setTelefone(jFTextFieldTelEdit.getText());
            fabricante.setCep(jFTextFieldCEPEdit.getText());
            fabricante.setLogradouro(jTextFieldLogrEdit.getText());
            fabricante.setNumero(Integer.parseInt(jTextFieldNumEdit.getText()));
            fabricante.setComplemento(jTextFieldCompEdit.getText());
            fabricante.setBairro(jTextFieldBairroEdit.getText());
            fabricante.setCidade(jTextFieldCidadeEdit.getText());
            fabricante.setUf(jCBoxUFEdit.getSelectedItem() + "");

            fachada.atualizar(fabricante);
            JOptionPane.showMessageDialog(this, "Fabricante alterado com sucesso.");

            atualizarLinha(fabricante);
            resetarCamposEdit();

            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane1.setEnabledAt(2, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jTextFieldNumEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumEditFocusLost
        // TODO add your handling code here:
        if (jTextFieldNumEdit.getText().isEmpty()) {
            jTextFieldNumEdit.setText("0");
        }
    }//GEN-LAST:event_jTextFieldNumEditFocusLost

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        previousTab = currentTab;
        currentTab = jTabbedPane1.getSelectedIndex();
        if (previousTab == 2) {
            jTabbedPane1.setEnabledAt(2, false);
        }
        if (currentTab == 0) {
            jFTextFieldCNPJ.requestFocusInWindow();
            jFTextFieldCNPJ.selectAll();
        } else if (currentTab == 2) {
            jTextFieldNmFantEdit.requestFocusInWindow();
            jTextFieldNmFantEdit.selectAll();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selectedRow = jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FabricanteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FabricanteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JButton jBtnDeletar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JComboBox<String> jCBoxUF;
    private javax.swing.JComboBox<String> jCBoxUFEdit;
    private javax.swing.JFormattedTextField jFTextFieldCEP;
    private javax.swing.JFormattedTextField jFTextFieldCEPEdit;
    private javax.swing.JFormattedTextField jFTextFieldCNPJ;
    private javax.swing.JFormattedTextField jFTextFieldCNPJEdit;
    private javax.swing.JFormattedTextField jFTextFieldTel;
    private javax.swing.JFormattedTextField jFTextFieldTelEdit;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBairroEdit;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCEPEdit;
    private javax.swing.JLabel jLabelCNPJ;
    private javax.swing.JLabel jLabelCNPJEdit;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCidadeEdit;
    private javax.swing.JLabel jLabelComp;
    private javax.swing.JLabel jLabelCompEdit;
    private javax.swing.JLabel jLabelLogr;
    private javax.swing.JLabel jLabelLogrEdit;
    private javax.swing.JLabel jLabelNmFant;
    private javax.swing.JLabel jLabelNmFantEdit;
    private javax.swing.JLabel jLabelNum;
    private javax.swing.JLabel jLabelNumEdit;
    private javax.swing.JLabel jLabelRazaoSoc;
    private javax.swing.JLabel jLabelRazaoSocEdit;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelTelEdit;
    private javax.swing.JLabel jLabelUF;
    private javax.swing.JLabel jLabelUFEdit;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPanel jPanelCadastar;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBairroEdit;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCidadeEdit;
    private javax.swing.JTextField jTextFieldComp;
    private javax.swing.JTextField jTextFieldCompEdit;
    private javax.swing.JTextField jTextFieldLogr;
    private javax.swing.JTextField jTextFieldLogrEdit;
    private javax.swing.JTextField jTextFieldNmFant;
    private javax.swing.JTextField jTextFieldNmFantEdit;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldNumEdit;
    private javax.swing.JTextField jTextFieldRazaoSoc;
    private javax.swing.JTextField jTextFieldRazaoSocEdit;
    // End of variables declaration//GEN-END:variables

    private void resetarCampos() {
        jFTextFieldCNPJ.setText("");
        jTextFieldNmFant.setText("");
        jTextFieldRazaoSoc.setText("");
        jFTextFieldTel.setText("");
        jFTextFieldCEP.setText("");
        jTextFieldLogr.setText("");
        jTextFieldNum.setText("0");
        jTextFieldComp.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jCBoxUF.setSelectedIndex(0);
        jFTextFieldCNPJ.requestFocusInWindow();
    }

    private void resetarCamposEdit() {
        jFTextFieldCNPJEdit.setText("");
        jTextFieldNmFantEdit.setText("");
        jTextFieldRazaoSocEdit.setText("");
        jFTextFieldTelEdit.setText("");
        jFTextFieldCEPEdit.setText("");
        jTextFieldLogrEdit.setText("");
        jTextFieldNumEdit.setText("0");
        jTextFieldCompEdit.setText("");
        jTextFieldBairroEdit.setText("");
        jTextFieldCidadeEdit.setText("");
        jCBoxUFEdit.setSelectedIndex(0);
    }

    private void adicionarLinha(Fabricante fabricante) {
        modeloAlterar.addRow(
                new Object[]{fabricante.getCnpj(), fabricante.getNomeFantasia(), fabricante.getRazaoSocial(),
                    fabricante.getTelefone(), fabricante.getCep(), fabricante.getLogradouro(), fabricante.getNumero(),
                    fabricante.getComplemento(), fabricante.getBairro(), fabricante.getCidade(), fabricante.getUf()}
        );
    }

    private void carregarTabela() {
        try {
            fabricantes = fachada.listar(new Fabricante());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        for (Fabricante f : fabricantes) {
            adicionarLinha(f);
        }
        jTable1.setModel(modeloAlterar);
    }

    private Fabricante getValues() throws Exception {
        if (selectedRow < 0) {
            throw new Exception("Nenhuma linha selecionada.");
        }
        Fabricante fabricante = new Fabricante();
        fabricante.setCnpj(jTable1.getValueAt(selectedRow, 0) + "");
        fabricante.setNomeFantasia(jTable1.getValueAt(selectedRow, 1) + "");
        fabricante.setRazaoSocial(jTable1.getValueAt(selectedRow, 2) + "");
        fabricante.setTelefone(jTable1.getValueAt(selectedRow, 3) + "");
        fabricante.setCep(jTable1.getValueAt(selectedRow, 4) + "");
        fabricante.setLogradouro(jTable1.getValueAt(selectedRow, 5) + "");
        fabricante.setNumero(Integer.parseInt(jTable1.getValueAt(selectedRow, 6) + ""));
        fabricante.setComplemento(jTable1.getValueAt(selectedRow, 7) + "");
        fabricante.setBairro(jTable1.getValueAt(selectedRow, 8) + "");
        fabricante.setCidade(jTable1.getValueAt(selectedRow, 9) + "");
        fabricante.setUf(jTable1.getValueAt(selectedRow, 10) + "");
        return fabricante;
    }

    /*private void editarTabela() {
        try {
            JFormattedTextField cellTel = new JFormattedTextField(new MaskFormatter("(##)####-####"));
            JFormattedTextField cellCEP = new JFormattedTextField(new MaskFormatter("##.###-###"));
            JTextField cellNum = new JTextField(new IntegerFilter(), "0", 0);
            JComboBox cellUF = new JComboBox(modeloUF);

            jTable1.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(cellTel));
            jTable1.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(cellCEP));
            jTable1.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(cellNum));
            jTable1.getColumnModel().getColumn(10).setCellEditor(new DefaultCellEditor(cellUF));
        } catch (ParseException ex) {
        }
    }*/
    private void atualizarLinha(Fabricante fabricante) {
        if (fabricante.getNomeFantasia() == null) {
            fabricante.setNomeFantasia("");
        }
        if (fabricante.getComplemento() == null) {
            fabricante.setComplemento("");
        }

        jTable1.setValueAt(fabricante.getNomeFantasia(), selectedRow, 1);
        jTable1.setValueAt(fabricante.getRazaoSocial(), selectedRow, 2);
        jTable1.setValueAt(fabricante.getTelefone(), selectedRow, 3);
        jTable1.setValueAt(fabricante.getCep(), selectedRow, 4);
        jTable1.setValueAt(fabricante.getLogradouro(), selectedRow, 5);
        jTable1.setValueAt(fabricante.getNumero(), selectedRow, 6);
        jTable1.setValueAt(fabricante.getComplemento(), selectedRow, 7);
        jTable1.setValueAt(fabricante.getBairro(), selectedRow, 8);
        jTable1.setValueAt(fabricante.getCidade(), selectedRow, 9);
        jTable1.setValueAt(fabricante.getUf(), selectedRow, 10);
    }
}
