/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import fabricante.Fabricante;
import fachada.Fachada;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import outros.IntegerFilter;
import outros.MyTableModel;

/**
 *
 * @author Matheus
 */
public class FabricanteGUI extends javax.swing.JFrame {

    /**
     * Creates new form FabricanteGUI
     */
    private final Fachada fachada = new Fachada();
    private ArrayList<Fabricante> fabricantes = new ArrayList<>();
    private final MyTableModel modeloAlterar = new MyTableModel(0, "CPNJ", "Nome Fantasia", "Razão Social", "Telefone", "CEP", "Logradouro", "Número", "Complemento", "Bairro", "Cidade", "UF");
    //private final DefaultComboBoxModel modeloUF = new DefaultComboBoxModel(new String[]{"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO"});
    private int selectedRow = -1;
    private int previousTab = -1, currentTab = -1;

    public FabricanteGUI() {
        initComponents();
        jTabbedPane1.setEnabledAt(2, false);
        //editarTabela();
        carregarTabela();
        jTable1.setModel(modeloAlterar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jTextFieldNomeFant = new javax.swing.JTextField();
        jTextFieldRazaoSoc = new javax.swing.JTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jTextFieldLogr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextFieldTel = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldComp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxUF = new javax.swing.JComboBox<>();
        jButtonCadastrar = new javax.swing.JButton();
        jTextFieldNum = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButtonDeletar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextFieldCNPJEdit = new javax.swing.JFormattedTextField();
        jTextFieldNomeFantEdit = new javax.swing.JTextField();
        jTextFieldRazaoSocEdit = new javax.swing.JTextField();
        jFormattedTextFieldCEPEdit = new javax.swing.JFormattedTextField();
        jTextFieldLogrEdit = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jFormattedTextFieldTelEdit = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldCompEdit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldCidadeEdit = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldBairroEdit = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxUFEdit = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jTextFieldNumEdit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("CNPJ:");

        jLabel2.setText("Nome Fantasia:");

        jLabel3.setText("Razão Social:");

        jLabel4.setText("CEP:");

        jLabel5.setText("Logradouro:");

        jLabel6.setText("Número:");

        jLabel9.setText("Cidade:");

        try {
            jFormattedTextFieldCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("Telefone:");

        try {
            jFormattedTextFieldTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Complemento:");

        jLabel8.setText("Bairro:");

        jLabel10.setText("UF:");

        jComboBoxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jTextFieldNum.setDocument(new IntegerFilter());
        jTextFieldNum.setText("0");
        jTextFieldNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRazaoSoc)
                            .addComponent(jFormattedTextFieldCEP)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addComponent(jTextFieldNum)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomeFant, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jTextFieldLogr)
                    .addComponent(jTextFieldComp)
                    .addComponent(jTextFieldCidade))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButtonCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeFant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldRazaoSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("OBS.: A alteração ocorre na linha selecionada.");

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButtonDeletar)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonEditar)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeletar)
                    .addComponent(jButtonEditar)))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        jLabel11.setText("CNPJ:");

        jLabel14.setText("Nome Fantasia:");

        jLabel15.setText("Razão Social:");

        jLabel16.setText("CEP:");

        jLabel17.setText("Logradouro:");

        jLabel18.setText("Número:");

        jFormattedTextFieldCNPJEdit.setEditable(false);
        try {
            jFormattedTextFieldCNPJEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCEPEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setText("Telefone:");

        try {
            jFormattedTextFieldTelEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel20.setText("Complemento:");

        jLabel21.setText("Cidade:");

        jLabel22.setText("Bairro:");

        jLabel23.setText("UF:");

        jComboBoxUFEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTextFieldNumEdit.setDocument(new IntegerFilter());
        jTextFieldNumEdit.setText("0");
        jTextFieldNumEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumEditFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jButtonSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCNPJEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRazaoSocEdit)
                            .addComponent(jFormattedTextFieldCEPEdit)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBoxUFEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addComponent(jTextFieldNumEdit)
                            .addComponent(jTextFieldBairroEdit))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCidadeEdit)
                    .addComponent(jTextFieldNomeFantEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldTelEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jTextFieldLogrEdit)
                    .addComponent(jTextFieldCompEdit))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jFormattedTextFieldCNPJEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldNomeFantEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldRazaoSocEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jFormattedTextFieldTelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jFormattedTextFieldCEPEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogrEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldCompEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextFieldBairroEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldCidadeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBoxUFEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButtonSalvar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Editar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumFocusLost
        // TODO add your handling code here:
        if (jTextFieldNum.getText().isEmpty()) {
            jTextFieldNum.setText("0");
        }
    }//GEN-LAST:event_jTextFieldNumFocusLost

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            Fabricante fabricante = new Fabricante();

            fabricante.setCnpj(jFormattedTextFieldCNPJ.getText());
            fabricante.setNomeFantasia(jTextFieldNomeFant.getText());
            fabricante.setRazaoSocial(jTextFieldRazaoSoc.getText());
            fabricante.setTelefone(jFormattedTextFieldTel.getText());
            fabricante.setCep(jFormattedTextFieldCEP.getText());
            fabricante.setLogradouro(jTextFieldLogr.getText());
            fabricante.setNumero(Integer.parseInt(jTextFieldNum.getText()));
            fabricante.setComplemento(jTextFieldComp.getText());
            fabricante.setComplemento(jTextFieldComp.getText());
            fabricante.setBairro(jTextFieldBairro.getText());
            fabricante.setCidade(jTextFieldCidade.getText());
            fabricante.setUf(jComboBoxUF.getSelectedItem() + "");

            fachada.inserir(fabricante);
            JOptionPane.showMessageDialog(this, "Fabricante inserido com sucesso.");

            adicionarLinha(fabricante);
            resetarCampos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        // TODO add your handling code here:
        try {
            Fabricante fabricante = getValues();

            fachada.remover(fabricante);
            JOptionPane.showMessageDialog(this, "Fabricante removido com sucesso.");

            modeloAlterar.removeRow(selectedRow);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        try {
            Fabricante fabricante = getValues();

            jFormattedTextFieldCNPJEdit.setText(fabricante.getCnpj());
            jTextFieldNomeFantEdit.setText(fabricante.getNomeFantasia());
            jTextFieldRazaoSocEdit.setText(fabricante.getRazaoSocial());
            jFormattedTextFieldTelEdit.setText(fabricante.getTelefone());
            jFormattedTextFieldCEPEdit.setText(fabricante.getCep());
            jTextFieldLogrEdit.setText(fabricante.getLogradouro());
            jTextFieldNumEdit.setText(fabricante.getNumero() + "");
            jTextFieldCompEdit.setText(fabricante.getComplemento());
            jTextFieldBairroEdit.setText(fabricante.getBairro());
            jTextFieldCidadeEdit.setText(fabricante.getCidade());
            jComboBoxUFEdit.setSelectedItem(fabricante.getUf());
            jTextFieldNomeFantEdit.selectAll();

            jTabbedPane1.setEnabledAt(2, true);
            jTabbedPane1.setSelectedIndex(2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        try {
            Fabricante fabricante = getValues();

            fabricante.setCnpj(jFormattedTextFieldCNPJEdit.getText());
            fabricante.setNomeFantasia(jTextFieldNomeFantEdit.getText());
            fabricante.setRazaoSocial(jTextFieldRazaoSocEdit.getText());
            fabricante.setTelefone(jFormattedTextFieldTelEdit.getText());
            fabricante.setCep(jFormattedTextFieldCEPEdit.getText());
            fabricante.setLogradouro(jTextFieldLogrEdit.getText());
            fabricante.setNumero(Integer.parseInt(jTextFieldNumEdit.getText()));
            fabricante.setComplemento(jTextFieldCompEdit.getText());
            fabricante.setBairro(jTextFieldBairroEdit.getText());
            fabricante.setCidade(jTextFieldCidadeEdit.getText());
            fabricante.setUf(jComboBoxUFEdit.getSelectedItem() + "");

            fachada.atualizar(fabricante);
            JOptionPane.showMessageDialog(this, "Fabricante alterado com sucesso.");

            atualizarLinha(fabricante);
            resetarCamposEdit();

            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane1.setEnabledAt(2, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jTextFieldNumEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumEditFocusLost
        // TODO add your handling code here:
        if (jTextFieldNumEdit.getText().isEmpty()) {
            jTextFieldNumEdit.setText("0");
        }
    }//GEN-LAST:event_jTextFieldNumEditFocusLost

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        previousTab = currentTab;
        currentTab = jTabbedPane1.getSelectedIndex();
        if (previousTab == 2) {
            jTabbedPane1.setEnabledAt(2, false);
        }
        if (currentTab == 0) {
            jFormattedTextFieldCNPJ.requestFocusInWindow();
        } else if (currentTab == 2) {
            jTextFieldNomeFantEdit.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selectedRow = jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FabricanteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FabricanteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxUF;
    private javax.swing.JComboBox<String> jComboBoxUFEdit;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEPEdit;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJEdit;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBairroEdit;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCidadeEdit;
    private javax.swing.JTextField jTextFieldComp;
    private javax.swing.JTextField jTextFieldCompEdit;
    private javax.swing.JTextField jTextFieldLogr;
    private javax.swing.JTextField jTextFieldLogrEdit;
    private javax.swing.JTextField jTextFieldNomeFant;
    private javax.swing.JTextField jTextFieldNomeFantEdit;
    private javax.swing.JTextField jTextFieldNum;
    private javax.swing.JTextField jTextFieldNumEdit;
    private javax.swing.JTextField jTextFieldRazaoSoc;
    private javax.swing.JTextField jTextFieldRazaoSocEdit;
    // End of variables declaration//GEN-END:variables

    private void resetarCampos() {
        jFormattedTextFieldCNPJ.setText("");
        jTextFieldNomeFant.setText("");
        jTextFieldRazaoSoc.setText("");
        jFormattedTextFieldTel.setText("");
        jFormattedTextFieldCEP.setText("");
        jTextFieldLogr.setText("");
        jTextFieldNum.setText("0");
        jTextFieldComp.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jComboBoxUF.setSelectedIndex(0);
        jFormattedTextFieldCNPJ.requestFocusInWindow();
    }

    private void resetarCamposEdit() {
        jFormattedTextFieldCNPJEdit.setText("");
        jTextFieldNomeFantEdit.setText("");
        jTextFieldRazaoSocEdit.setText("");
        jFormattedTextFieldTelEdit.setText("");
        jFormattedTextFieldCEPEdit.setText("");
        jTextFieldLogrEdit.setText("");
        jTextFieldNumEdit.setText("0");
        jTextFieldCompEdit.setText("");
        jTextFieldBairroEdit.setText("");
        jTextFieldCidadeEdit.setText("");
        jComboBoxUFEdit.setSelectedIndex(0);
    }

    private void adicionarLinha(Fabricante fabricante) {        
        modeloAlterar.addRow(
                new Object[]{fabricante.getCnpj(), fabricante.getNomeFantasia(), fabricante.getRazaoSocial(),
                    fabricante.getTelefone(), fabricante.getCep(), fabricante.getLogradouro(), fabricante.getNumero(),
                    fabricante.getComplemento(), fabricante.getBairro(), fabricante.getCidade(), fabricante.getUf()}
        );
    }

    private void carregarTabela() {
        try {
            fabricantes = fachada.listar(new Fabricante());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        for (Fabricante f : fabricantes) {
            adicionarLinha(f);
        }
    }

    private Fabricante getValues() throws Exception {
        if (selectedRow < 0) {
            throw new Exception("Nenhuma linha selecionada.");
        }
        Fabricante fabricante = new Fabricante();
        fabricante.setCnpj(jTable1.getValueAt(selectedRow, 0) + "");
        fabricante.setNomeFantasia(jTable1.getValueAt(selectedRow, 1) + "");
        fabricante.setRazaoSocial(jTable1.getValueAt(selectedRow, 2) + "");
        fabricante.setTelefone(jTable1.getValueAt(selectedRow, 3) + "");
        fabricante.setCep(jTable1.getValueAt(selectedRow, 4) + "");
        fabricante.setLogradouro(jTable1.getValueAt(selectedRow, 5) + "");
        fabricante.setNumero(Integer.parseInt(jTable1.getValueAt(selectedRow, 6) + ""));
        fabricante.setComplemento(jTable1.getValueAt(selectedRow, 7) + "");
        fabricante.setBairro(jTable1.getValueAt(selectedRow, 8) + "");
        fabricante.setCidade(jTable1.getValueAt(selectedRow, 9) + "");
        fabricante.setUf(jTable1.getValueAt(selectedRow, 10) + "");
        return fabricante;
    }

    /*private void editarTabela() {
        try {
            JFormattedTextField cellTel = new JFormattedTextField(new MaskFormatter("(##)####-####"));
            JFormattedTextField cellCEP = new JFormattedTextField(new MaskFormatter("##.###-###"));
            JTextField cellNum = new JTextField(new IntegerFilter(), "0", 0);
            JComboBox cellUF = new JComboBox(modeloUF);

            jTable1.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(cellTel));
            jTable1.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(cellCEP));
            jTable1.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(cellNum));
            jTable1.getColumnModel().getColumn(10).setCellEditor(new DefaultCellEditor(cellUF));
        } catch (ParseException ex) {
        }
    }*/
    private void atualizarLinha(Fabricante fabricante) {
        if (fabricante.getNomeFantasia() == null) {
            fabricante.setNomeFantasia("");
        }
        if (fabricante.getComplemento()== null) {
            fabricante.setComplemento("");
        }
        
        jTable1.setValueAt(fabricante.getNomeFantasia(), selectedRow, 1);
        jTable1.setValueAt(fabricante.getRazaoSocial(), selectedRow, 2);
        jTable1.setValueAt(fabricante.getTelefone(), selectedRow, 3);
        jTable1.setValueAt(fabricante.getCep(), selectedRow, 4);
        jTable1.setValueAt(fabricante.getLogradouro(), selectedRow, 5);
        jTable1.setValueAt(fabricante.getNumero(), selectedRow, 6);
        jTable1.setValueAt(fabricante.getComplemento(), selectedRow, 7);
        jTable1.setValueAt(fabricante.getBairro(), selectedRow, 8);
        jTable1.setValueAt(fabricante.getCidade(), selectedRow, 9);
        jTable1.setValueAt(fabricante.getUf(), selectedRow, 10);
    }
}
